opt_in_rules:
  - private_outlet
  - force_unwrapping
  - strong_iboutlet
  - private_action
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - identical_operands
  
  - unneeded_parentheses_in_closure_argument
  - let_var_whitespace
  - yoda_condition
  - closure_spacing
  - collection_alignment
  - operator_usage_whitespace
  - closure_end_indentation
  - file_name_no_space
  - unowned_variable_capture
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - empty_collection_literal
disabled_rules:
  - trailing_whitespace
  - type_name

# Rule Config
line_length: 150
identifier_name:
  min_length: 1
  max_length:
    warning: 40
    error: 60
type_name:
  min_length: 3
  max_length:
    warning: 80
    error: 100

excluded:
  - Pods
  - R.generated.swift
